# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  profile: chill
  request_changes_workflow: false
  auto_review:
    enabled: true
    base_branches:
      - develop
      - main
